[[main]]
weight = 1
name = "Home"
url = "#"

[[main]]
weight = 1
name = "Laptops "
url = "/Laptops/"
parent = "Best Pic"

[[main]]
weight = 2
name = "Motherboards"
url = "/Motherboards/"
parent = "Best Pic"

[[main]]
weight = 3
name = "Ram"
url = "/Ram/"
parent = "Best Pic"

[[main]]
weight = 1
name = "Knowledge Base"
url = "/Knowledge Base/"

[[footer]]
weight = 1
name = "Elements"
url = "/elements/"

[[footer]]
weight = 1
name = "Contact Form"
url = "/contact-form/"