[[main]]
weight = 1
name = "Home"
url = "#"

[[main]]
weight = 1
name = "Knowledge Base"
url = "/Knowledge Base/"

[[main]]
weight = 2
name = "Laptops "
url = "/Laptops/"
parent = "Best Pics"

[[main]]
weight = 1
name = "Motherboards"
url = "https://techlaptop.xyz/motherboards/"
parent = "Best Pics"

[[main]]
weight = 4
name = "Ram"
url = "/Ram/"
parent = "Best Pics"

[[footer]]
weight = 1
name = "Elements"
url = "/elements/"

[[footer]]
weight = 1
name = "Contact Form"
url = "/contact-form/"