[[main]]
weight = 1
name = "Home"
url = "#"

[[main]]
weight = 2
name = "Laptops "
url = "/Laptops/"
parent = "Best Pic"

[[footer]]
weight = 1
name = "Elements"
url = "/elements/"

[[footer]]
weight = 1
name = "Contact Form"
url = "/contact-form/"